/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -m -a dockadaptor -i kbddock.h -l KbdDock /home/cosmos/Softwares/Projects/CoreBox/kvkbd/src/org.corebox.kvkbd.Dock.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "dockadaptor.h"

#include <QtCore>
#include <QtGui>

#if QT_VERSION >= 0x050000
	#include <QtWidgets>
#endif

/*
 * Implementation of adaptor class DockAdaptor
 */

DockAdaptor::DockAdaptor(KbdDock *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DockAdaptor::~DockAdaptor()
{
    // destructor
}

bool DockAdaptor::visible() const
{
    // get the value of property visible
    return qvariant_cast< bool >(parent()->property("visible"));
}

void DockAdaptor::setVisible(bool value)
{
    // set the value of property visible
    parent()->setProperty("visible", QVariant::fromValue(value));
}
