/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -m -a kvkbdadaptor -i mainwidget.h -l MainWidget /home/cosmos/Softwares/Projects/CoreBox/kvkbd/src/org.corebox.kvkbd.Kvkbd.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "kvkbdadaptor.h"

#include <QtCore>
#include <QtGui>

#if QT_VERSION >= 0x050000
	#include <QtWidgets>
#endif

/*
 * Implementation of adaptor class KvkbdAdaptor
 */

KvkbdAdaptor::KvkbdAdaptor(MainWidget *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

KvkbdAdaptor::~KvkbdAdaptor()
{
    // destructor
}

bool KvkbdAdaptor::alone() const
{
    // get the value of property alone
    return qvariant_cast< bool >(parent()->property("alone"));
}

bool KvkbdAdaptor::locked() const
{
    // get the value of property locked
    return qvariant_cast< bool >(parent()->property("locked"));
}

void KvkbdAdaptor::setLocked(bool value)
{
    // set the value of property locked
    parent()->setProperty("locked", QVariant::fromValue(value));
}

bool KvkbdAdaptor::visible() const
{
    // get the value of property visible
    return qvariant_cast< bool >(parent()->property("visible"));
}

void KvkbdAdaptor::setVisible(bool value)
{
    // set the value of property visible
    parent()->setProperty("visible", QVariant::fromValue(value));
}
